// Kept in sync with server/src/utils/geography.ts (separate client/server
// projects, no shared package to import across). Reference data for the
// "where is this school" fields on the onboarding form — Africa-first
// country list, Nigeria-only state list (see that file's comment for why).
export const COUNTRIES = [
  "Nigeria",
  "Ghana",
  "Kenya",
  "South Africa",
  "Uganda",
  "Rwanda",
  "Benin",
  "Burkina Faso",
  "Cameroon",
  "Central African Republic",
  "Chad",
  "Congo-Brazzaville",
  "Côte d'Ivoire",
  "Equatorial Guinea",
  "Gabon",
  "Guinea-Bissau",
  "Mali",
  "Niger",
  "Senegal",
  "Togo",
] as const;

export const NIGERIAN_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "Federal Capital Territory",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;
