// Reference data for the "where is this school" fields on the onboarding
// form. Countries are scoped to markets this platform actually targets —
// Africa-first, same reasoning as finance.dafsolt.cloud's Currency enum —
// not the full list of world countries, so the dropdown doesn't imply
// support that doesn't exist yet. States are Nigeria-only for the same
// reason: it's the one market with first-class rollout today, so it's the
// one that gets a curated dropdown instead of a free-text field.
export const COUNTRIES = [
  "Nigeria",
  "Ghana",
  "Kenya",
  "South Africa",
  "Uganda",
  "Rwanda",
  "Benin",
  "Burkina Faso",
  "Cameroon",
  "Central African Republic",
  "Chad",
  "Congo-Brazzaville",
  "Côte d'Ivoire",
  "Equatorial Guinea",
  "Gabon",
  "Guinea-Bissau",
  "Mali",
  "Niger",
  "Senegal",
  "Togo",
] as const;

export const NIGERIAN_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "Federal Capital Territory",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;
